# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1097, 628)
        Dialog.setStyleSheet("")
        self.Fundo = QtWidgets.QLabel(Dialog)
        self.Fundo.setEnabled(False)
        self.Fundo.setGeometry(QtCore.QRect(-20, -20, 1131, 671))
        self.Fundo.setAutoFillBackground(False)
        self.Fundo.setStyleSheet("image: url(:/img/APS - BIOMETRIA.png);")
        self.Fundo.setText("")
        self.Fundo.setObjectName("Fundo")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(360, 60, 451, 151))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("font: 75 22pt \"Arial\";\n"
"color: rgb(0, 255, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(310, 260, 211, 51))
        self.label_2.setStyleSheet("font: 75 12pt \"Arial\";\n"
"color: rgb(0, 255, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(310, 310, 131, 51))
        self.label_3.setStyleSheet("font: 75 12pt \"Arial\";\n"
"color: rgb(0, 255, 0);")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(420, 270, 171, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(650, 410, 93, 28))
        self.pushButton.setStyleSheet("\n"
"font: 8pt \"Arial\";")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(430, 470, 311, 21))
        self.label_4.setStyleSheet("font: 75 pt \"Arial\";\n"
"color: rgb(0, 255, 0);")
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(420, 320, 171, 31))
        self.lineEdit_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "ACESSO RESTRITO"))
        self.label_2.setText(_translate("Dialog", "USUÁRIO:"))
        self.label_3.setText(_translate("Dialog", "SENHA:"))
        self.pushButton.setText(_translate("Dialog", "ENTRAR"))
        self.label_4.setText(_translate("Dialog", "SOMENTE NIVEL AUTORIZADO"))
import img


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_login()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
